### ISSUE TITLE
Windows files are ELF

### ISSUE THREAD

**Issue by gd4c** [tsak/xlsx2json-api#1]
Hi,

I downloaded the Windows files from the releases page, but they wouldn't work. Upon examination, they turned out to be Linux executables.

Could you please fix them?

**Comment by tsak** [comment]
Apologies for taking so long to notice the issue. This was a bug in the `.github/build` script which resulted in all builds to be `linux/amd64`. Fixed in cbd3e299e96a955abbbcdc92783627463695b792

I've also updated the binaries in the [1.0.1 release](https://github.com/tsak/xlsx2json-api/releases/tag/v1.0.1).

Thanks for pointing this out and taking the time to check.
